### ISSUE TITLE
Fix after upgrading discord.py version from 1.7.3 to 2.x.x (latest)

### ISSUE THREAD

**Issue by neihousaigaai** [dnh-bot/dnh-werewolf-bot#214]
There are many big changes after upgrading discord.py version to 2.x.x. 

For example:

```
discord.utils.get(...)
A helper that returns the first element in the iterable that meets all the traits passed in attrs. This is an alternative for find().

Changed in version 2.0: The iterable parameter is now positional-only.

Changed in version 2.0: The iterable parameter supports asynchronous iterables.
```
caused an error:

```
RuntimeWarning: coroutine 'DiscordInterface.delete_channel' was never awaited
  *[player.delete_personal_channel() for player in self.players.values()]
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
'NoneType' object has no attribute 'delete_personal_channel'
```
